### ISSUE TITLE
UI doesnt want to start

### ISSUE THREAD

**Issue by sauliuni** [Sable/mclab-ide#11]
Hello,

i wanted to try out the project. If i use the zipped git export from github:

 After vagrant up everything works like it should be, but at the end after vagrant up get following error:

`==> default: Successfully installed Flask Flask-Assets cssmin jsmin sh pyzmq numpy pymatbridge Werkzeug Jinja2 itsdangerous webassets MarkupSafe
==> default: Cleaning up...
==> default: fatal: Not a git repository (or any parent up to mount point /vagrant)
==> default: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`

After starting the webserver i get following error:

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 125-976-590
10.0.2.2 - - [25/Jan/2017 09:33:56] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/ide/views.py", line 19, in index
    return render_template('index.html', projects=get_all_projects())
  File "/usr/local/lib/python3.4/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.4/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/vagrant/ide/templates/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/vagrant/ide/templates/layout.html", line 12, in top-level template code
    {% assets 'css_app' %}
  File "/usr/local/lib/python3.4/dist-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/local/lib/python3.4/dist-packages/webassets/bundle.py", line 806, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/webassets/bundle.py", line 777, in _urls
    *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/webassets/bundle.py", line 765, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/webassets/bundle.py", line 619, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/local/lib/python3.4/dist-packages/webassets/bundle.py", line 543, in _merge_and_apply
    kwargs=item_data)
  File "/usr/local/lib/python3.4/dist-packages/webassets/merge.py", line 276, in apply
    return self._wrap_cache(key, func)
  File "/usr/local/lib/python3.4/dist-packages/webassets/merge.py", line 218, in _wrap_cache
    content = func().getvalue()
  File "/usr/local/lib/python3.4/dist-packages/webassets/merge.py", line 251, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/usr/local/lib/python3.4/dist-packages/webassets/filter/less.py", line 139, in input
    self._apply_less(_in, out, source_path)
  File "/usr/local/lib/python3.4/dist-packages/webassets/filter/less.py", line 131, in _apply_less
    self.subprocess(args, out, in_)
  File "/usr/local/lib/python3.4/dist-packages/webassets/filter/__init__.py", line 527, in subprocess
    proc.returncode, stdout, stderr))
webassets.exceptions.FilterError: less: subprocess returned a non-success result code: 1, stdout=b'', stderr=b'\x1b[31mFileError: \'../bower_components/bootstrap/less/bootstrap.less\' wasn\'t found\x1b[39m\x1b[31m in \x1b[39m-\x1b[90m on line 1, column 1:\x1b[39m\n1 \x1b[7m\x1b[31m\x1b[1m@\x1b[22mimport "../bower_components/bootstrap/less/bootstrap.less";\x1b[39m\x1b[27m\n\x1b[90m2 \x1b[39m\x1b[0m\x1b[0m\n\n'

If i clone it, i get following error from vagrant
==> default: Submodule 'support/mclab' (https://github.com/Sable/mclab) registered for path 'support/mclab'
==> default: Cloning into 'support/mclab'...
==> default: fatal: could not read Username for 'https://github.com': No such device or address
==> default: Clone of 'https://github.com/Sable/mclab' into submodule path 'support/mclab' failed

**Comment by isbadawi** [comment]
I'll take a look at this later today. One thing is that the Sable/mclab repo was split up and then made private, so I'll have to change the submodule to point to the Sable/mclab-core repo instead. I'll try the VM after fixing that and see if there other issues.

**Comment by isbadawi** [comment]
Should be fixed -- please try again with the latest commit.
Note you'll need to run `git submodule update` after pulling.
